spring:
  redis:
    #Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码
    password: 123456
    #Redis数据库索引（默认为0）
    database: 0
    #连接超时时间（毫秒）
    timeout: 5000

sms:
  accessKeyId: LTAI5tMNX1tzWP4DQ1uzNXXg
  accessKeySecret: sXNCZHmlmdIE9VXbWSQaR5fgeA8e72
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  signName: 阿里云短信测试
  templateCode: SMS_154950909